version: '3.9'

services:

  social-feed-prod:
    container_name: nwolf083-social-feed-prod
    image: nwolf083/socialfeedprod
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8080:80"